# _config.yml
title: Sean O'Mara
author: Sean O'Mara
description: Personal Site of Sean O'Mara

# Social links
github_username: smomara
twitter_username: mseanomara
linkedin_username: omarams

# Build settings
markdown: kramdown
permalink: /blog/:title/
